config/routes.rb
Rails.application.routes.draw do
  get 'search', to: 'frontend#search', as: :jobs_search_path
  get 'job/:id/:title', to: 'frontend#job', :id => /\d+/, as: :job
  get 'company/:id/:name', to: 'frontend#company', :id => /\d+/, as: :company

  get 'signup', to: 'users#signup', as: :signup
  post 'user/create', to: 'users#create', as: :user_create
  get 'user/created', to: 'users#created', as: :user_created
  get 'user/activate/:activation_code', to: 'users#activate', as: :user_activate
  get 'signin', to: 'users#signin', as: :signin
  post 'user/auth', to: 'users#auth', as: :user_auth

  get 'panel', to: 'backend#index', as: :backend

  get 'panel/company/profile', to: 'companies#profile', as: :company_profile
  match 'panel/company/save' => 'companies#save', as: :company_save, via: [:post, :patch]

  get 'panel/jobs/', to: 'jobs#index', as: :jobs_index

  root 'frontend#index'

end

app/models/company.rb
class Company < ActiveRecord::Base
  validates :name, presence: true, length: { minimum: 3 }
  validates :brief_description, presence: true
  validates :description, presence: true
  validates :website, :url => {:allow_null => true, :allow_blank => true}

  belongs_to :user
  has_many :jobs

  def self.find_active(id)
    where(active: true)
      .find(id)
  end
end

app/models/job.rb
class Job < ActiveRecord::Base
  belongs_to :company

  searchable do
    text :title, :brief_description, :description
    boolean :active
    text :company do
      company.name
    end
  end

  def self.search_all(criteria)
    query = search do
      fulltext criteria
      with :active, true
    end
    self.results_where_company_is_active query.results
  end

  def self.find_all_active
    select('jobs.id, jobs.title, jobs.brief_description, jobs.company_id')
      .joins(:company)
      .where('companies.active = ? AND jobs.active = ?', true, true)
  end

  def self.find_active(id)
    where('jobs.active = ? AND companies.active = ?', true, true)
      .joins(:company)
      .find(id)
  end

  def self.find_active_by_company_id(id)
    where('companies.id = ? AND jobs.active = ? AND companies.active = ?', id, true, true)
      .joins(:company)
  end

  private
  def self.results_where_company_is_active(results)
    filtered_results = []
    results.each do |job|
      if job.company.active
        filtered_results << job
      end
    end
    filtered_results
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_one :company

  has_secure_password

  before_create do
    self.active = false
    self.activation_code = RandomToken.gen 9
  end

  validates :name, presence: true, length: { minimum: 2 }, uniqueness: true
  validates :password, length: { minimum: 8 }, on: :create
  validates :email, uniqueness: true
  validates_email_format_of :email, check_mx: true

  def self.activate(activation_code)
    user = where(active: false)
      .find_by_activation_code!(activation_code)
    user.active = true
    user.save!
    user
  end

  def self.auth(username, password)
    user = self.find_by(active: true, name: username)
    return unless user
    user.authenticate(password)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/backend_controller.rb
class BackendController < ApplicationController
  include Loggable

  def index
    user = User.find session[:user_id]
    redirect_to company_profile_path unless user.company
  end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  include Loggable

  def profile
    @user = User.find session[:user_id]
    @company = @user.company || Company.new
  end

  def save
    @user = User.find session[:user_id]
    if @user.company
      @company = @user.company
    else
      @company = @user.company || Company.new(company_params)
      @company.user = @user
    end

    respond_to do |format|
      if request.post? and @company.save or request.patch? and @company.update company_params
        format.html { redirect_to backend_path, notice: 'Company was successfully saved.' }
      else
        format.html { render :profile }
      end
    end
  end

  private
  def company_params
    params.require(:company)
      .permit(:name, :brief_description, :description, :website)
  end
end

app/controllers/concerns/loggable.rb
module Loggable extend ActiveSupport::Concern
  included do
    before_filter :redirect_if_user_not_logged_in
  end

  private
  def redirect_if_user_not_logged_in
    redirect_to signin_path unless session[:user_id]
  end
end

app/controllers/frontend_controller.rb
class FrontendController < ApplicationController
  def index
    @jobs = Job.find_all_active
  end

  def search
    @jobs = Job.search_all params[:q]
  end

  def job
    begin
      @job = Job.find_active params[:id]
    rescue ActiveRecord::RecordNotFound
      render_404 and return
    end

    if params[:title] != @job.title.parameterize
      redirect_to job_url(@job.id, @job.title.parameterize), :status => 303
    end
  end

  def company
    begin
      @company = Company.find_active params[:id]
      @jobs = Job.find_active_by_company_id @company.id
    rescue ActiveRecord::RecordNotFound
      render_404 and return
    end

    if params[:name] != @company.name.parameterize
      redirect_to company_url(@company.id, @company.name.parameterize), :status => 303
    end
  end

  private
  def render_404
    render file: "#{Rails.root}/public/404.html" , status: :not_found
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  include Loggable

  def index
    user = User.find session[:user_id]
    @jobs = user.company.jobs
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def signup
    @user = User.new
  end

  def create
    @user = User.new user_params
    respond_to do |format|
      captcha_message = 'Incorrect CAPTCHA data. Please try again.'
      if !verify_recaptcha(model: @user, message: captcha_message) || !@user.save(context: :create)
        format.html { render :signup }
      else
        UserMailer.activate(@user).deliver_later
        format.html { redirect_to :user_created }
      end
    end
  end

  def created
  end

  def signin
    redirect_to backend_path if session[:user_id]
  end

  def auth
    user = User.auth params[:name], params[:password]
    if user
      session[:user_id] = user.id
      redirect_to backend_path
    else
      redirect_to signin_path, notice: 'The username or password you entered is incorrect.'
    end
  end

  def activate
    begin
      @user = User.activate params[:activation_code]
      @success = true
    rescue ActiveRecord::RecordNotFound
      @success = false
    end
  end

  private
  def user_params
    params.require(:user)
      .permit(:name, :password, :password_confirmation, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/backend/index.html.erb
<%= render 'backend/shared/menu' %>

app/views/backend/shared/_menu.html.erb
<%= link_to 'Profile', :company_profile %>
<%= link_to 'Jobs', :jobs_index %>

app/views/companies/_form.html.erb
<%= form_for @company, url: company_save_path do |company_form| %>
  <% if @company.errors.any? %>
    <ul>
    <% @company.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  <% end %>

  <%= company_form.label :name %>
  <%= company_form.text_field :name %>
  <%= company_form.label :brief_description %>
  <%= company_form.text_field :brief_description, :placeholder => "Leading Rails Company" %>
  <%= company_form.label :description %>
  <%= company_form.text_area :description, :placeholder => "We are a product-focused company where software development ..." %>
  <%= company_form.label :website %>
  <%= company_form.text_field :website %>
  <%= company_form.submit "Save" %>
<% end %>

app/views/companies/profile.html.erb
<% if not @company.new_record? %>
  <%= render 'backend/shared/menu' %>
<% end %>
<p>Company Profile</p>
<%= render 'form' %>

app/views/frontend/_jobs_list.html.erb
<% if @jobs.any? %>
  <% @jobs.each do |job| %>
    <article>
      <p><%= link_to job.title, job_path(job.id, job.title.parameterize) %></p>
      <p><%= link_to job.company.name, company_path(job.company.id, job.company.name.parameterize) %></p>
      <p><%= job.brief_description %></p>
    </article>
  <% end %>
<% else %>
  <p>There is no open job position.</p>
<% end %>

app/views/frontend/_search.html.erb
<%= form_tag :jobs_search_path, method: 'get' do %>
  <%= label_tag :q, 'Search:' %>
  <%= text_field_tag :q, params[:q], :placeholder => 'Ninja Rails 5 Developer' %>
<% end %>

app/views/frontend/company.html.erb
<article>
  <p><%= @company.name %></p>
  <p><%= link_to @company.website, @company.website %></p>
  <p><%= @company.description %></p>
</article>
<article>
  <p>Open Jobs</p>
  <% @jobs.each do |job| %>
    <p><%= link_to job.title, job_path(job.id, job.title.parameterize) %></p>
    <p><%= job.brief_description %></p>
  <% end %>
</article>

app/views/frontend/index.html.erb
<%= render 'jobs_list' %>

app/views/frontend/job.html.erb
<article>
  <p><%= @job.title %></p>
  <p><%= link_to @job.company.name, company_path(@job.company.id, @job.company.name.parameterize) %></p>
  <p><%= @job.description %></p>
  <p><%= @job.application_instructions %></p>
</article>

app/views/frontend/search.html.erb
<%= render 'search' %>
<%= render 'jobs_list' %>

app/views/jobs/index.html.erb
<%= render 'backend/shared/menu' %>
<% if not @jobs.empty? %>
  <table>
    <tr>
      <th>Title</th>
      <th>Brief Description</th>
    </tr>
    <% @jobs.each do |job| %>
      <tr>
        <td><%= job.title %></td>
        <td><%= job.brief_description %></td>
      </tr>
    <% end %>
  </table>
<% else %>
  <p>You don't have any job.</p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Jobs</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/_create_user_form.html.erb
<%= form_for @user, url: create_user_path do |form| %>

  <% if @user.errors.any? %>
    <ul>
      <% @user.errors.full_messages.each do |error| %>
        <li><%= error %></li>
      <% end %>
    </ul>
  <% end %>

  <%= form.label :name, 'Username' %>
  <%= form.text_field :name %>
  <%= form.label :password, 'Password' %>
  <%= form.password_field :password %>
  <%= form.label :password_confirmation, 'Password confirmation' %>
  <%= form.password_field :password_confirmation %>
  <%= form.label :email %>
  <%= form.text_field :email %>
  <%= recaptcha_tags %>
  <%= form.submit 'Sign Up' %>
<% end %>

app/views/users/_form.html.erb
<%= form_for @user, url: user_create_path do |form| %>

  <% if @user.errors.any? %>
    <ul>
      <% @user.errors.full_messages.each do |error| %>
        <li><%= error %></li>
      <% end %>
    </ul>
  <% end %>

  <%= form.label :name, 'Username' %>
  <%= form.text_field :name %>
  <%= form.label :password, 'Password' %>
  <%= form.password_field :password %>
  <%= form.label :password_confirmation, 'Password confirmation' %>
  <%= form.password_field :password_confirmation %>
  <%= form.label :email %>
  <%= form.text_field :email %>
  <%= recaptcha_tags %>
  <%= form.submit 'Sign Up' %>
<% end %>

app/views/users/activate.html.erb
<% if @success %>
<%= @user.name %>, your user was successfully activated.
<% else %>
This user was already activated or the activation code is invalid.
<% end %>

app/views/users/created.html.erb
<p>User created.</p>

app/views/users/signin.html.erb
<% if flash[:notice] %>
  <p><%= flash[:notice] %></p>
<% end %>
<%= form_tag user_auth_path, method: 'post' do %>
  <%= label_tag :name, 'Username' %>
  <%= text_field_tag :name, nil, autofocus: true %>
  <%= label_tag :password %>
  <%= password_field_tag :password %>
  <%= submit_tag 'Login' %>
<% end %>

app/views/users/signup.html.erb
<%= render 'form' %>

app/views/users/user_activate.html.erb
<% if @success %>
<%= @user.name %>, your user was successfully activated.
<% else %>
This user was already activated or the activation code is invalid.
<% end %>

app/views/users/user_created.html.erb
<p>User created.</p>